language: ruby
rvm: '2.5'
env:
  global:
  - BUNDLE_PATH=${TRAVIS_BUILD_DIR}/vendor/bundle
cache:
  directories:
  - ${BUNDLE_PATH}
script: bundle exec exe/miq build all
deploy:
  provider: script
  skip_cleanup: true
  script: curl -sSL https://raw.githubusercontent.com/ManageIQ/manageiq.github.io/build/trigger.sh | bash -s
  on:
    branch: master
